server:
  port: 8080

spring:
  application:
    name: Main-Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
instance:
  hostname: localhost